### ISSUE TITLE
Error when creating the view - Cannot read property 'getQuickFilter' of undefined

### ISSUE THREAD

**Issue by gurpreet-5555** [SAP-samples/fiori-elements-incident-management#3]
Getting error 'Cannot read property 'getQuickFilter' of undefined' while loading list report page.

![image](https://user-images.githubusercontent.com/63334405/106725733-b1f43600-662f-11eb-90fd-c2bac4b71f92.png)

Console:
![image](https://user-images.githubusercontent.com/63334405/106725672-a30d8380-662f-11eb-81da-c0da8cbce141.png)

UI5 version:
![image](https://user-images.githubusercontent.com/63334405/106725870-d51ee580-662f-11eb-8bd4-9b017d838032.png)

**Comment by ARiesterer** [comment]
Hi gurpreet-5555
at which step of the tutorial is this error showing up?
I just checked the process until the List Report is shown the first time after generating the application. Worked well on my side. The UI5 version seems to be the same (1.85.3, see image).

Best regards
Andreas Riesterer
SAP SE

![image](https://user-images.githubusercontent.com/9048637/106999722-fc3bfb00-6786-11eb-846d-bba95ecda4fd.png)

**Comment by ShilpaRGowda** [comment]
I am facing the same issue in my app,any help will be appreciated!

**Comment by ShilpaRGowda** [comment]
Hi @gurpreet-5555 if you have found the solution for this error please share it here even I am facing the same issue!

**Comment by ARiesterer** [comment]
no feedback since months - therefore closing the issue
