### ISSUE TITLE
SQLITE_ERROR: no such column: priority.name

### ISSUE THREAD

**Issue by jcailan** [SAP-samples/fiori-elements-incident-management#4]
I'm getting an error:

`SQLITE_ERROR: no such column: priority.name`

I just did below:
- Clone repo down to local VS Code
- Switch branch to `sampleSolution`
- Do `npm install`
- Do `cds watch`
- Open the Fiori App
- Clicked `Go` button

![image](https://user-images.githubusercontent.com/27951983/107925248-22477380-6faf-11eb-8cb4-5abaf82e2e3c.png)

**Comment by sjvans** [comment]
Hi @jcailan 

We don't yet support query options with path expressions on SQLite, i.e., in your case $orderby:'priority/name'. It's on the roadmap for 2021. Also, we are currently working on a HANA vs. SQLite feature overview for future reference.

Best,
Sebastian

**Comment by ARiesterer** [comment]
Hi @jcailan
I have fixed this in the git repository, i.e. by again cloning the service and generating the application this error should not show up anymore when pressing the Go button within the application.
Best Regards
Andreas

**Comment by jcailan** [comment]
Thanks for your response @D051664 Andreas!
I can see that you avoided the path expressions issue since it was not supported yet in SQLite.

https://github.com/SAP-samples/fiori-elements-incident-management/commit/0513e037492506d031401e613b581eff2f0b3bd4
