### ISSUE TITLE
Error when creating the view - Cannot read property 'getQuickFilter' of undefined

### ISSUE THREAD

**Issue by ShilpaRGowda** [SAP-samples/fiori-elements-incident-management#5]
I am getting the below error while loading the list report page.
![image](https://user-images.githubusercontent.com/85287061/123418167-5cb4c300-d5d6-11eb-8d51-ccb621a86f3e.png)
![image](https://user-images.githubusercontent.com/85287061/123418306-84a42680-d5d6-11eb-92d3-9c6942605698.png)
![image](https://user-images.githubusercontent.com/85287061/123418645-eb294480-d5d6-11eb-86e0-4a8211fb1881.png)

**Comment by ARiesterer** [comment]
@ShilpaRGowda
I have just tried to reproduce this issue by running through the tutorial until the step where the generated application is started the first time to open the ListReport - no issues on my side.
The trial account UI5 version used is 1.91
 ![image](https://user-images.githubusercontent.com/9048637/125572574-03ba2d90-e40e-49f4-bc4f-23ac7cb4276e.png)
Can you check the version and build date on your side?
Best regards
Andreas

**Comment by ARiesterer** [comment]
No feedback yet, therefore closing the issue.
